version: '3'

services:
    sti:
      build:
          context: .
          dockerfile: Dockerfile
      env_file:
          - .env
      ports:
          - "${SERVICE_PORT}:5000"
      volumes:
          - ./:/www